### ISSUE TITLE
Add Graph Data Structure

### ISSUE THREAD

**Issue by freebird1195** [no-stack-dub-sack/cs-playground-react#10]
Most common & imp Graph Algos

**Comment by no-stack-dub-sack** [comment]
Hi @freebird1195, thanks for the suggestion! Are you up for making a PR to add this to the app?

**Comment by supamunkey** [comment]
@no-stack-dub-sack I'll see if I can get one in if no one else jumps on it 🏃

**Comment by no-stack-dub-sack** [comment]
@supamunkey that sounds perfect! To be honest, it's one that I'm not familiar with yet, and I'm busy with a ton of other stuff right now, so if someone wanted to add it, I'd be super grateful, because then I can learn it myself as well! 

I have added a few new features since the article was released (mainly the clear console button), but learning this might not be possible for me until after the new year. So maybe give @freebird1195 another day or so in case she wanted to do it, and if not, I'd say just go for it.

**Comment by no-stack-dub-sack** [comment]
@supamunkey I'm gonna say all yours if you want it!

**Comment by freebird1195** [comment]
@supamunkey @no-stack-dub-sack Hey! I am sorry guys I wasn't available all this while.
The thing is I have never worked on React. I am just starting to learn it.
@supamunkey Go ahead with it. :) Once I get started with React, I will try and contribute on other issues.

**Comment by no-stack-dub-sack** [comment]
@freebird1195 I think one thing that's missing from this repo is contributing guidelines, which I'll make it a point to write up soon. The thing is, React knowledge is by no means a pre-requisite to a simple contribution like adding a topic to cover. @supamunkey did a great job of figuring it out, but I should def provide some instructions now that there's some interest in improving the app from outside contributors!

If you have any more ideas @freebird1195, let me know! I'd be happy to provide some info on how to contribute, and I promise, you won't need to write a single line of React code!
