### ISSUE TITLE
Any Menu Click Crashes

### ISSUE THREAD

**Issue by roopkt** [no-stack-dub-sack/cs-playground-react#23]
Run npm start
Click on any option from the left side menu you see below screen

![capture](https://user-images.githubusercontent.com/330383/33851451-0f897e28-de85-11e7-83f5-a6f1db59e7ee.PNG)

**Comment by no-stack-dub-sack** [comment]
@roopkt but the app fully loads first? What version of IE is that?

The app is running fine for me, locally and on the live site, so there has to be something else affecting things. It looks like the `for...of` loop is failing, which is shouldn't in modern browsers. I also thought babel would compile this down to ES5, but it looks like the most likely culprit right now (because of lack of Symbol.iterator support?):

![image](https://user-images.githubusercontent.com/18563015/33964991-5b9fa14e-e028-11e7-885e-8eb6277659af.png)

Can you try running the app in chrome and see if that changes things?

**Comment by roopkt** [comment]
HI I am also testing it in chrome and it crashes. I use IE 11. 
Never mind if you think it is working then mostly I will have to download the entire code newly and try it out.

**Comment by no-stack-dub-sack** [comment]
@roopkt yeah, I would recommend forking it and re-cloning it in it's current state, because everything seems to be working on my end. It looks like it's failing on that `for...of` loop which it shouldn't be if the the click handler is working correctly and the store was correctly hydrated. From here, I can't really see why this wouldn't be working. I've never run the app on a PC, but other than browser incompatibility (which you've ruled out), I don't see why it wouldn't run on a PC, there isn't anything platform specific here that I know of.

**Comment by no-stack-dub-sack** [comment]
@roopkt any luck with this?

**Comment by no-stack-dub-sack** [comment]
closing as stale. @roopkt feel free to reopen if you're still having any problems.
