### ISSUE TITLE
aside not responsive below 42% width

### ISSUE THREAD

**Issue by brisourceful** [no-stack-dub-sack/cs-playground-react#32]
When the width of the aside is adjusted to below 42% the span elements are no longer inline with the div container styling. The aside is not responsive when the viewport is minimized.

![screen shot 2018-01-21 at 4 55 58 pm](https://user-images.githubusercontent.com/22714001/35201008-061b016a-fecc-11e7-9b72-757ebaa68831.png)

**Comment by no-stack-dub-sack** [comment]
Hey @brisourceful, thanks for opening this issue. Yes, I've def noticed this before, and have been wondering what to do about it for a while. Overall, the site really isn't optimized for smaller screen sizes. Since this is an in-browser coding project, I figured smaller-screen optimization could be sort of low on the priority list, but ideally, I'd eventually like to make the site fully responsive, to the point where on smaller screens, the menu and console are hidden by default and can be opened by click/touch. 

In the meantime, what are your thoughts on what the best solution is?

I'm working on a big PR (#25), and have a bandaid for this worked in: essentially, below a certain width, the console pane just slides all the way up, hiding the menu, which reappears when you get past that same breakpoint. This really just avoids the real problem of poor responsiveness, but does hide the ugly results. What do you think? 

P.S. Once this big PR is in, I'm really going to be looking for active contributors to help take the site to the next level! If you're interested, please let me know!

**Comment by brisourceful** [comment]
Sorry for the super delay in my reply. I've been slammed at work. I think the update looks a lot better and is more responsive. I'm happy to help here and there when I can as I find this project very valuable.

**Comment by no-stack-dub-sack** [comment]
@brisourceful no worries, and glad to hear you find the project useful! If you ever have any extra time, I'd still welcome the contributions. I think the biggest need at this point is to improve the content - especially the algorithms section. So if you know of any cool challenges, hopefully adding them in isn't too painful (though this is something that could be worked on, as it does require editing at least a couple of files right now).

Anyway, a new PR has recently been merged which improves the menu UI ten-fold, so I think this problem is non-existent at this point.
