### ISSUE TITLE
Markdown syntax on welcome page.

### ISSUE THREAD

**Issue by bluenex** [no-stack-dub-sack/cs-playground-react#4]
I get that the welcome page of the site is the same as `readme.md`. However with console style, there is no way to render these markdown syntax properly. For example line 15 should be rewritten as `the codebase, the repo lives at https://github.com/no-stack-dub-sack/cs-playground-react.` instead. And for other text styling syntax, we can just remove them like `- _SAVING CODE_` to `- SAVING CODE`.

https://github.com/no-stack-dub-sack/cs-playground-react/blob/29f09cf5615b134c72d8ecc4f85c2d4df72b7da2/src/assets/seed/welcome.js#L15-L21

If you think this is not necessary or this is actually your intention, you can close the issue right away. 😄

**Comment by no-stack-dub-sack** [comment]
Hey @bluenex! Thanks for your comments - this was, however, intentional. Initially, I just left the editor in JS mode for the welcome message, but written as one big comment, it was kind of hard to get things to stand out. So I changed the editor to MD mode just for this one view in order to get some syntax highlighting that could make certain things standout. 

Admittedly, the link syntax on line 15 is probably not necessary, but the rest of it I think helps some of the headings to stand out a bit. Do you see the headers, like SAVING CODE, in blue, like pictured below?

![image](https://user-images.githubusercontent.com/18563015/33159399-9fba3b1c-cfe0-11e7-84c1-425312925f99.png)

**Comment by no-stack-dub-sack** [comment]
closing as stale... feel free to reopen if you'd like to continue the conversation!
