### ISSUE TITLE
BST algo remove has small glitch

### ISSUE THREAD

**Issue by mansisce** [no-stack-dub-sack/cs-playground-react#80]
We are not handling the both left and right pointers when we delete the node.  Update will be as mentioned below 			
			
// node only has right child
                        else if (!node.left) {
				node.value = node.right.value
				node.right = node.right.right
                                **_node.left = node.right.left;_**
			}
			// node only has left child
			else if (!node.right) {
				node.value = node.left.value
				node.left = node.left.left
                                **_node.right = node.left.right_**
			}

**Comment by no-stack-dub-sack** [comment]
Hi @mansisce Thanks for picking this out! I've actually been meaning to update this solution for a while, but it will also require some changes to tests, as I think some of them are a bit too brittle. I'm going to go ahead and make these changes now and will have you review when I'm done.

**Comment by no-stack-dub-sack** [comment]
Hi @mansisce, disregard my last message if you saw it before I deleted it. I forgot I already had made changes to the BST solution a while back :-)

You are quite right, nice catch! Really, the better solution would just be `node = node.right` and `node = node.left`, respectively, but for some reason I can't figure out, this messes up trying to remove the root node of a tree with only two nodes, e.g. 

![image](https://user-images.githubusercontent.com/18563015/46908992-53a06800-cef9-11e8-8219-061e5c6fc038.png)

if the solution is:

```js
// node only has right child
else if (!node.left) {
  node = node.right;
}
// node only has left child
else if (!node.right) {
  node = node.left;
}
```

and then you run `tree.remove(15)`, the tree is unchanged, when really the root node should be 27. Which, frankly, does not make sense to me!

Anyway, to keep this working, I think you need to make the assignments in bold above the original assignments, e.g.:

```js
// node only has right child
else if (!node.left) {
    node.value = node.right.value;
    node.left = node.right.left; // here
    node.right = node.right.right;
}
// node only has left child
else if (!node.right) {
    node.value = node.left.value;
    node.right = node.left.right; // here
    node.left = node.left.left;
}
```

Otherwise, an example like this wouldn't work if you tried to delete `17`
![image](https://user-images.githubusercontent.com/18563015/46909297-e2af7f00-cefd-11e8-9e96-7218f688ae75.png)

because if the code was like this:
```js
else if (!node.left) {
    node.value = node.right.value;
    node.right = node.right.right;
    // now, node.right is null after the above line executes
    node.left = node.right.left; 
}
```

`node.right.left` would fail. To protect against this, you need to assign the node on the side that we're not replacing first. 

Do you want to go ahead and make this change? Thanks again for catching this pretty serious bug, if there was a lot of data in the other pointer, it would all get lost in a real world implementation!

**Comment by mansisce** [comment]
Let me raise the PR if that is not already done.

**Comment by mansisce** [comment]
Why do you have base64.js file. For divider you could have used css properties and classes.  Why are you using VERTICAL_GRIP and HORIZONTAL_GRIP

**Comment by no-stack-dub-sack** [comment]
@mansisce I forget exactly why now.... but I think I borrowed those base64 images from a library called Split.JS and just liked the way they looked. I believe I played around with some styling for the grips using only CSS, but didn't really like the way they came out. Using the background image instead of other styling worked fine and looked good.

**Comment by mansisce** [comment]
Not able to push to a branch which I've created and hence not able to raise a PR for the same.

**Comment by no-stack-dub-sack** [comment]
@mansisce what's the issue with pushing the branch?
